version: 0.2

phases:
  pre_build:
    commands:
      - mvn test
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/EncoraMavenTomcatWebApp.war
